config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get 'sidebar' => 'mobile_nav#show_sidebar', as: 'sidebar'
  get 'stats' => 'mobile_nav#stats', as: 'stats'

  resources :email_notifications, only: [:create, :update, :delete]

  get 'notices/new'

  get 'notices/create'

#  if Rails.env.development?
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
#  end

  resources :photo_galleries

  get 'search/index'

  get 'notifications/index'
  get 'notifications/render_read'
  get 'notifications/:id' => 'notifications#show' # , as: 'notification'

  resources 'group_maintainers', only: [:create, :destroy]

  resources :groups

  post 'groups/add_user_to_group'

  resources 'group_memberships', only: [:create, :destroy]

  resources 'likes', only: [:create, :destroy]
  resources :comments

  resources :contacts

  get 'home' => 'static_pages#home'

  # root 'static_pages#home'
  # root 'users#show'
  get 'about' => 'static_pages#about'

  get 'invitation_required' => 'static_pages#invitation_required'

  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :invitations => 'users/invitations'
  }
  resource :custom_appearance, only: [:show, :update]
  post 'custom_appearances/change_color'
  post 'custom_appearances/blogroll'
  delete 'custom_appearances/delete_blog'
# root 'public#index'

  authenticated :user do
    # root 'users#index'
    # :root
    root 'static_pages#home'
  end

  unauthenticated :user do
    devise_scope :user do
      # get '/' => 'devise/sessions#new'
      # :root
      root 'static_pages#home'
    end
  end

  get '/messages' => redirect('/conversations')
  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      get :sentbox
      post :empty_trash
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :invites, only: [:new, :create]
  get 'invites/dele' => 'invites#dele', as: 'dele'

  resources :microposts
  resources :photos, only: [:destroy, :show]
  get '/:slug/:id' => 'microposts#show', as: 'user_post'
  get 'new' => 'microposts#new_user_post', as: 'new_user_post'
  resources :relationships, only: [:create, :destroy]

  get '/:id' => 'users#show', as: 'single_user'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  helper_method :mailbox, :conversation
  before_action :mailbox
  before_action :inbox_trash_count

  def create
    recipient_emails = conversation_params(:recipients).split(',')
    recipients = User.where(email: recipient_emails).all
    conversation = current_user.
        send_message(recipients, *conversation_params(:body, :subject)).conversation
  end

  def index
    @conversations ||= @mailbox.inbox.page(params[:page]).per(5)
    #@trash ||= current_user.mailbox.trash.all

  end

  def sentbox
    @sentbox ||= @mailbox.sentbox.page(params[:page]).per 5
  end

  def reply
    current_user.reply_to_conversation(conversation, params[:body])
    participants_ids = []
    sender_id = params[:sender_id].to_i
    conversation.participants.each do |participant|
      if participant.id != sender_id
        participants_ids.push(participant.id)
      end
    end
    participants_ids.each do |p_id|
      ReadPost.create(entity_type: conversation.class, user_id: p_id, read: false, entity_type_id: conversation.id, user_notified: false)
      ActionCable.server.broadcast "conversation_#{p_id}_messages",
                                   text: "Donner Wetter",
                                   conversation_id: conversation.id
    end
    redirect_to conversation_path(@conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to request.referrer
  end

  def show
    @conversation ||= @mailbox.conversations.find(params[:id])
    ReadPost.update_read_post_as_read(@conversation.id, current_user.id, @conversation.class)
    conversation.mark_as_read(current_user)
  end

  def show_notification
    @notification ||= @mailbox.notifications.find(params[:id])
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :back
  end

  def trashbin
    @conversations ||= @mailbox.inbox.page(params[:page]).per(25)
    @conversationscount ||= @mailbox.inbox.all
    @trash ||= @mailbox.trash.page(params[:page]).per(25)
  end

  def empty_trash
    current_user.mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(:deleted => true)
    end
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def inbox_trash_count
    @conversationscount ||= @mailbox.inbox.count
    @trashcount ||= @mailbox.trash.count
    @sentcount ||= @mailbox.sentbox.count
  end

end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_inbox_trash.html.erb
<h4>conversations</h4>
<p>
  <a href="<%= conversations_path %>"><%= @conversationscount %> Inbox </a>
  | <a href="<%= trashbin_conversations_path %>"><%= @trashcount %> Trash</a>
  | <a href="<%= sentbox_conversations_path %>"><%= @sentcount %> Sent</a>
</p>

app/views/conversations/index.html.erb
<div class="row">
  <div class="col-md-4">

     <%= render 'inbox_trash' %>

    <% if @conversations.nil? || @conversations.empty? %>
        <p>
          your inbox folder is currently empty
        </p>
    <% end %>

    <%#= render 'notifications/notifications' %>

  </div>
  <div class="col-md-5">

    <h4>inbox:</h4>

    <% @conversations.each do |conversation| %>

        <% if conversation.is_read?(current_user) %>
             <%= link_to conversation.subject, conversation_path(conversation) %>
        <% else %>
            <b><%= link_to conversation.subject, conversation_path(conversation) %></b>
        <% end %>

        <br> von:
        <% conversation.participants.each do |participant| %>
            <% if participant != current_user %>
                <%# if conversation.is_read?(current_user) %>
                    <%= participant.name %>
                <%# else %>
                    <b><%#= participant.name %></b>
                <%# end %>
            <% end %>
        <% end %>

        <%# if conversation.is_read?(current_user) %>
            <small><%= conversation.updated_at.strftime('%e.%m.%Y at %H:%M') %></small>
        <%# else %>
            <b><%#= conversation.updated_at.strftime('%a, %m/%e/%Y %I:%M %p') %></b>
        <%# end %>

        <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, { :controller => 'conversations', :action => 'trash', :id => conversation.id }, :title => 'move to trash', :method => 'post' %>

        <br><br>
    <% end %>

    <%= paginate @conversations %>


  </div>
</div>

app/views/conversations/sentbox.html.erb
<div class="row">
  <div class="col-md-4">

    <%= render 'inbox_trash' %>

    <% if @sentbox.nil? || @sentbox.empty? %>
        <p>
          unfortunately your sent box is currently empty, maybe you would like to write someone a letter?
        </p>
    <% end %>
  </div>
  <div class="col-md-6">
    <h4>Sent Box:</h4>
    <% @sentbox.each do |conversation| %>

        <% if conversation.is_read?(current_user) %>
            <%= link_to conversation.subject, conversation_path(conversation) %>
        <% else %>
            <b><%= link_to conversation.subject, conversation_path(conversation) %> </b>
        <% end %>

        <br>an:
        <% conversation.participants.each do |p| %>
            <% if p != current_user %>
                <%= link_to p.name, single_user_path(p) %>
            <% end %>
        <% end %>
        <small>
          <%= conversation.updated_at.strftime('%e.%m.%Y at %H:%M') %>
        </small>
        <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, { :controller => 'conversations', :action => 'trash', :id => conversation.id }, :title => 'move to trash', :method => 'post' %>
            <br><br>

    <% end %>
    <small>
      <%= paginate @sentbox %>
    </small>

  </div>
</div>

app/views/conversations/show.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'inbox_trash' %>
  </div>

  <div class="col-md-7">

    <div>
      <% @conversation.participants.each do |participant| %>
        <% if participant != current_user %>
          conversation with: <b><%= participant.name %></b>
        <% end %>
      <% end %>
    </div>
    <div style="padding: 1em;">
      <b><%= @conversation.subject %></b>
    </div>
    <div id="scroll_box" class="conversation_box">
      <table class="table table-striped">
        <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
        </thead>


        <tbody>
        <%= content_tag_for(:div, @conversation.receipts_for(current_user).order(:created_at => :asc)) do |receipt| %>
          <% message = receipt.message %>


          <tr>
            <% if message.sender.avatar_url.nil? %>
              <td><%= image_tag message.sender.gravatar_url, width: '25', class: 'img-circle' %></td>
            <% else %>
              <td><%= image_tag message.sender.avatar.thumb, width: '25', class: 'img-circle' %></td>
            <% end %>
            <td>
              <%= simple_format(auto_link(strip_tags(message.body))) %>
              <small>
                <b><%= link_to message.sender.name, message.sender %></b>
                &nbsp;&nbsp;&nbsp;<%= message.created_at.strftime('%e.%m. at %H:%M') %>
              </small>
            </td>
          </tr>


        <% end %>

        </tbody>

      </table>
    </div>
    <%= render 'messages/form', :conversation => @conversation %>

  </div>
</div>

<script>
    $('#scroll_box').scrollTop($('#scroll_box')[0].scrollHeight);
</script>

app/views/conversations/trashbin.html.erb
<div class="row">
  <div class="col-md-4">

    <%= render 'inbox_trash' %>



    <% if @trash.nil? || @trash.empty? %>
        <p>
          unfortunately your trash folder is currently empty, maybe you delete a conversation
        </p>
    <% end %>

  </div>
  <div class="col-md-5">

    <h4>trash bin:</h4>

    <% @trash.each do |conversation| %>

        <%= link_to conversation.subject, conversation_path(conversation) %><br>


        <% conversation.participants.each do |participant| %>
            <% if participant != current_user %>
            <% end %>
            <% if participant != current_user %>
                <b><%= participant.name %></b>
            <% end %>
        <% end %>

        <%= link_to '<span class="glyphicon glyphicon-inbox"></span>'.html_safe, {:controller => 'conversations', :action => 'untrash', :id => conversation.id}, :title => 'back to inbox!!', method: 'post' %>
        <small><%= conversation.updated_at.strftime('%e.%m.%Y at %I:%M') %></small>

        <br><br>
    <% end %>

    <%= paginate @trash %>
    <p>
        <% if @trashcount > 0 %>
            <%= button_to 'empty trash', 'empty_trash', data: {:confirm => 'Empty Trash? These conversations will be roasting forever in the purgatory!'}, class: 'btn btn-primary btn-danger' %>
        <% end %>
    </p>

  </div>
</div>