config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get 'sidebar' => 'mobile_nav#show_sidebar', as: 'sidebar'
  get 'stats' => 'mobile_nav#stats', as: 'stats'

  resources :email_notifications, only: [:create, :update, :delete]

  get 'notices/new'

  get 'notices/create'

#  if Rails.env.development?
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
#  end

  resources :photo_galleries

  get 'search/index'

  get 'notifications/index'
  get 'notifications/render_read'
  get 'notifications/:id' => 'notifications#show' # , as: 'notification'

  resources 'group_maintainers', only: [:create, :destroy]

  resources :groups

  post 'groups/add_user_to_group'

  resources 'group_memberships', only: [:create, :destroy]

  resources 'likes', only: [:create, :destroy]
  resources :comments

  resources :contacts

  get 'home' => 'static_pages#home'

  # root 'static_pages#home'
  # root 'users#show'
  get 'about' => 'static_pages#about'

  get 'invitation_required' => 'static_pages#invitation_required'

  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :invitations => 'users/invitations'
  }
  resource :custom_appearance, only: [:show, :update]
  post 'custom_appearances/change_color'
  post 'custom_appearances/blogroll'
  delete 'custom_appearances/delete_blog'
# root 'public#index'

  authenticated :user do
    # root 'users#index'
    # :root
    root 'static_pages#home'
  end

  unauthenticated :user do
    devise_scope :user do
      # get '/' => 'devise/sessions#new'
      # :root
      root 'static_pages#home'
    end
  end

  get '/messages' => redirect('/conversations')
  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      get :sentbox
      post :empty_trash
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :invites, only: [:new, :create]
  get 'invites/dele' => 'invites#dele', as: 'dele'

  resources :microposts
  resources :photos, only: [:destroy, :show]
  get '/:slug/:id' => 'microposts#show', as: 'user_post'
  get 'new' => 'microposts#new_user_post', as: 'new_user_post'
  resources :relationships, only: [:create, :destroy]

  get '/:id' => 'users#show', as: 'single_user'

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :mailbox

  def index
    @notifications ||= @mailbox.notifications.page(params[:page]).per(10)
    @all_notifications_count ||= @mailbox.notifications(read: false).count
    @hintergrund = current_user.custom_appearance
    # @galleries = current_user.photo_galleries
    # @latest_photo_comments = current_user.latest_photo_comments.limit(10)
    # @mailbox.notifications(read: false).each do |unread|
    #   unread.mark_as_read current_user
    # end
  end

  def show
    @notification = Mailboxer::Notification.find(params[:id])
    @notification.mark_as_read current_user
    redirect_to notifications_index_path
  end

  def render_read
    @mailbox.notifications(read: false).each do |unread|
      unread.mark_as_read current_user
    end
    redirect_to root_url
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification_partial.html.erb
<%#= link_to notifications_index_path, :title => 'notifications', data: {
                  container: 'body',
                  toggle: 'popover',
                  trigger: 'focus',
                  placement: 'bottom',
                  content: @notifications.inspect
              } do %>
<a href="#" data-toggle="popover" data-placement="bottom" data-container="body" data-content="<%= current_user.mailbox.notifications.inspect %>">
  <span style="font-size: 1.2em;" class="glyphicon glyphicon-bell"></span>
  <% if current_user.mailbox.notifications(:read => false ).count != 0 %>
      <span class="badge"><%= current_user.mailbox.notifications(:read => false).count %></span>
  <% end %>
</a>
<%# end %>

app/views/notifications/_notifications.html.erb
<h4>notifications</h4>
<% @notifications.each do |notification| %>

    <% if notification.is_unread?(current_user) %>
        <div id="notification_box" onmouseout="<%= notification.mark_as_read current_user %>" style="background: #eee; padding: 10px; padding-left: 15px; border: 1px solid #ccc; border-radius: 5px;">
            <small><%= notification.subject %></small><br>
            <%= notification.body.html_safe %><br>
            <small><%= notification.created_at.strftime('%d.%m.%y %H:%M') %></small><br>
        </div>

    <% else %>
        <div style="padding: 10px; padding-left: 15px; border: 1px solid #efefef; border-radius: 5px;">
        <small><%= notification.subject %></small><br>
        <%= notification.body.html_safe %><br>
        <small><%= notification.created_at.strftime('%d.%m.%y %H:%M') %></small><br>
        </div>
    <% end %>

<% end %>

app/views/notifications/index.html.erb
<div class="row">
  <div class="col-md-4">
    <%= render 'shared/current_user_info' %>
  </div>
  <div class="col-md-6">

    <% if @all_notifications_count != 0 %>
      <%= link_to 'Mark all ' + @all_notifications_count.to_s + ' as read', notifications_render_read_path, remote: true, class: 'btn btn-info' %>
    <% end %>

    <%= render 'notifications' %>
    <%= paginate @notifications %>
  </div>

</div>

app/views/notifications/show.html.erb
<h1>Notification#show</h1>
<p>Find me in app/views/notification/show.html.erb</p>

<%= @notification.inspect %>