config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  get 'sidebar' => 'mobile_nav#show_sidebar', as: 'sidebar'
  get 'stats' => 'mobile_nav#stats', as: 'stats'

  resources :email_notifications, only: [:create, :update, :delete]

  get 'notices/new'

  get 'notices/create'

#  if Rails.env.development?
  require 'sidekiq/web'
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end
#  end

  resources :photo_galleries

  get 'search/index'

  get 'notifications/index'
  get 'notifications/render_read'
  get 'notifications/:id' => 'notifications#show' # , as: 'notification'

  resources 'group_maintainers', only: [:create, :destroy]

  resources :groups

  post 'groups/add_user_to_group'

  resources 'group_memberships', only: [:create, :destroy]

  resources 'likes', only: [:create, :destroy]
  resources :comments

  resources :contacts

  get 'home' => 'static_pages#home'

  # root 'static_pages#home'
  # root 'users#show'
  get 'about' => 'static_pages#about'

  get 'invitation_required' => 'static_pages#invitation_required'

  devise_for :users, :controllers => {
      :registrations => 'users/registrations',
      :invitations => 'users/invitations'
  }
  resource :custom_appearance, only: [:show, :update]
  post 'custom_appearances/change_color'
  post 'custom_appearances/blogroll'
  delete 'custom_appearances/delete_blog'
# root 'public#index'

  authenticated :user do
    # root 'users#index'
    # :root
    root 'static_pages#home'
  end

  unauthenticated :user do
    devise_scope :user do
      # get '/' => 'devise/sessions#new'
      # :root
      root 'static_pages#home'
    end
  end

  get '/messages' => redirect('/conversations')
  resources :messages do
    member do
      post :new
    end
  end

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
    collection do
      get :trashbin
      get :sentbox
      post :empty_trash
    end
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :invites, only: [:new, :create]
  get 'invites/dele' => 'invites#dele', as: 'dele'

  resources :microposts
  resources :photos, only: [:destroy, :show]
  get '/:slug/:id' => 'microposts#show', as: 'user_post'
  get 'new' => 'microposts#new_user_post', as: 'new_user_post'
  resources :relationships, only: [:create, :destroy]

  get '/:id' => 'users#show', as: 'single_user'

end

app/models/photo_gallery.rb
class PhotoGallery < ApplicationRecord
  include CreateUpdateQueue
  #tracked owner: ->(controller, model) { controller && controller.current_user}
  has_many :photos
  accepts_nested_attributes_for :photos
  has_and_belongs_to_many :users
  # has_one :notice, dependent: :destroy
  has_many :notices
  validates :title, presence: true

  after_create :trigger_the_create_queue
  after_update :trigger_the_update_queue

end

app/controllers/photo_galleries_controller.rb
class PhotoGalleriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_photo_gallery, only: [:show, :edit, :update, :destroy]
  before_action :photo_gallery_user, only: [:edit, :update, :destroy]
  before_action :the_index, only: :index
  before_action :photo_gallery_params_nil, only: [:create, :update]

  respond_to :html

  def index
    @photo_galleries = PhotoGallery.all
    respond_with(@photo_galleries)
  end

  def show
    @photos = @photo_gallery.photos
    respond_with(@photo_gallery)
  end

  def new
    @photo_gallery = PhotoGallery.new
    respond_with(@photo_gallery)
    @photo = @photo_gallery.photos.build
  end

  def edit
    @photos = @photo_gallery.photos
  end

  def create
    @photo_gallery = current_user.photo_galleries.build(photo_gallery_params) # PhotoGallery.new(photo_gallery_params)
    @photo_gallery.users << current_user
    if @photo_gallery.save
      if params[:photos].nil?
        puts 'the fucking photo params are not what they are expected'
      else
        params[:photos]['picture'].each do |photo|
          puts current_user.inspect
          @photo = @photo_gallery.photos.create!(picture: photo, photo_gallery_id: @photo_gallery.id, user_id: current_user.id)
        end
      end
    end
    redirect_to(@photo_gallery)
  end

  def update
    if @photo_gallery.update(photo_gallery_params)
      if params[:photos].nil?
        puts 'the photos is nil'
      else
        puts params[:photos]
        params[:photos]['picture'].each do |photo|
          @photo = @photo_gallery.photos.create!(picture: photo, photo_gallery_id: @photo_gallery.id, user_id: current_user.id)
        end
      end

      flash[:success] = 'jepp'
    end
    respond_with(@photo_gallery)
  end

  def destroy
    @photo_gallery.destroy
    respond_with(@photo_gallery)
  end

  private

    def set_photo_gallery
      @photo_gallery = PhotoGallery.find(params[:id])
    end

    def photo_gallery_params
      params.require(:photo_gallery).permit(:title, :description, :last_updated_by_id, photos_attributes: [:id, :photo_gallery_id, :picture])
    end

    def photo_gallery_user
      if !@photo_gallery.users.include? current_user
        flash[:danger] = 'so nicht!'
        redirect_to root_path
      end
    end

    def the_index
      if !current_user.admin?
        flash[:danger] = 'langsam wirds fad'
        redirect_to root_path
      end
    end

    def photo_gallery_params_nil
      photo_gallery_params.each do |param|
        if param[0] == 'title'
          if !param[1] == ''

          elsif param[1] == ''
            flash[:danger] = 'maaahh'
            redirect_to request.referer
          end
        end
      end
    end

end

app/helpers/photo_galleries_helper.rb
module PhotoGalleriesHelper
  def user_photo_galleries(user)
    user.photo_galleries
  end
end

app/views/photo_galleries/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_for(@photo_gallery, html: {multipart: true}) do |f| %>
        <%# if @photo_gallery.errors.any? %>
            <!--<div id="error_explanation">
              <%#= pluralize(@photo_gallery.errors.count, 'error') %> prohibited this gallery from being saved:

                <%#= @photo_gallery.errors.inspect %>
                <%# @photo_gallery.errors.full_messages.each do |message| %>

                <%# end %>

            </div>-->


        <%# end %>

        <div class="form-group">
          <%= f.text_field :title, class: 'form-control', placeholder: 'Title must not be blank' %>
        </div>
        <div class="form-group">
          <%= f.hidden_field :last_updated_by_id, :value => current_user.id %>
          <%= f.text_area :description, class: 'form-control', placeholder: 'Description' %>
        </div>
        <%#= f.file_field :picture, multiple: true, name: 'photos[picture][]' %>
        <%= render 'shared/upload_button' %>

        <div class="form-group">
          <%= f.submit 'submit this', class: 'btn btn-default' %>
        </div>
    <% end %>
  </div>
</div>


<script>
  window.onload = init();
</script>

app/views/photo_galleries/edit.html.erb
<h5>Editing <b><%= @photo_gallery.title %></b></h5>

<div class="row">
    <% @photos.each do |photo| %>
        <div class="col-md-1 the_single_photo-<%= photo.id %>">
          <%= image_tag photo.picture.thumb, width: 50 %>
          <%= link_to 'delete', photo_path(photo.id), method: :delete, remote: true, data: { confirm: 'Sicher? Das war es dann ...' } %>
        </div>
    <% end %>
</div>
<br>
<%= render 'form' %>

<%= link_to 'Show', @photo_gallery %> |
<%= link_to 'Back', request.referer %>

app/views/photo_galleries/index.html.erb
<h1>Listing photo_galleries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_galleries.each do |photo_gallery| %>
      <tr>
        <td><%= photo_gallery.title %></td>
        <td><%= photo_gallery.description %></td>
        <% photo_gallery.users.each do |u| %>
            <td><%= u.name %></td>
              <% end %>
        <td><%= link_to 'Show', photo_gallery %></td>
        <td><%= link_to 'Edit', edit_photo_gallery_path(photo_gallery) %></td>
        <td><%= link_to 'Destroy', photo_gallery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo gallery', new_photo_gallery_path %>

app/views/photo_galleries/new.html.erb
<h4>New Photo Gallery</h4>

<%= render 'form' %>

<%= link_to 'Back', request.referer %>

app/views/photo_galleries/show.html.erb
<% provide(:title, @photo_gallery.title ) %>
<div class="row">

  <div class="col-md-1">
    <p id="notice"><%= notice %></p>
    <% @photo_gallery.users.each do |user| %>
        <% if user.avatar_url.nil? %>
            <%= image_tag user.gravatar_url, width: 32, class: 'img-rounded' %>
        <% else %>
            <%= image_tag user.avatar.thumb, class: 'img-rounded', width: 32 %>
        <% end %>
        <small><%= link_to user.name, single_user_path(user) %></small>
    <% end %>

  </div>
  <div class="col-md-5">

      <b><%= @photo_gallery.title %></b><br>

      <%= @photo_gallery.description %>

  </div>
</div>
<hr>
<div class="container-fluid">
  <div class="row">

    <% i = 0 %>

    <% @photos.each do |photo| %>
        <% i = i +1 %>
        <% inti = i.to_s %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <%= link_to photo_path(photo) do %>
              <span class="photo_in_gallery">
                <%= image_tag(photo.picture, id: 'image' + inti, class: 'img') %>
              </span>
              <span class="photo_in_gallery">
                <small><%= pluralize(photo.comments.count, 'comment') %></small>
              </span>

          <% end %>

        </div>
    <% end %>

  </div>
</div>


<hr>

<%= link_to 'Edit', edit_photo_gallery_path(@photo_gallery) %> |
<%= link_to 'Back', request.referer %>

<style>
    .fullscreen:-moz-full-screen {
        width: auto !important;
        height: auto !important;
        margin:auto !important;
    }

    .img {
        max-width: 100%;
        max-height: 300px;
        margin-right: 15px;
        margin-top: 15px;
    }

    .photo_in_gallery {
        display: block;
    }

</style>

<script>

    function full() {

        console.log(document.getElementById('image1'));
        var image_element = document.getElementById('image1');
        if (document.fullscreenEnabled) {
            console.log('true');
        } else if (document.mozFullScreenEnabled) {
            //console.log('mozFull');
            image_element.mozRequestFullScreen();
        }
    }
</script>